apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api-deployment
  namespace: rust-server
  labels:
    app: rust-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api-container
          image: julienben/rust-learning:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: mongouri-secret
                  key: MONGOURI
      imagePullSecrets:
        - name: image-registries-secret
